LetsHangOut/config/routes.rb
Rails.application.routes.draw do
	get 'welcome/index'

  resources :personas
  resources :restaurantes
	resources :productos
	resources :compras
	resources :pagos

  root "welcome#index"
end

LetsHangOut/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

LetsHangOut/app/models/compra.rb
class Compra < ApplicationRecord
  has_many :detalle_compras
  has_many :personas, through: :detalle_compras
  has_many :productos, through: :detalle_compras
	belongs_to :restaurante
end

LetsHangOut/app/models/detalle_compra.rb
class DetalleCompra < ApplicationRecord
  belongs_to :compra
  belongs_to :persona
  belongs_to :producto
end

LetsHangOut/app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :persona
end

LetsHangOut/app/models/persona.rb
class Persona < ApplicationRecord
  has_many :detalle_compras
  has_many :compras, through: :detalle_compras
  has_many :productos, through: :detalle_compra
	has_many :pagos
end

LetsHangOut/app/models/producto.rb
class Producto < ApplicationRecord
	belongs_to :restaurante
end

LetsHangOut/app/models/restaurante.rb
class Restaurante < ApplicationRecord
  has_many :productos
end

LetsHangOut/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

LetsHangOut/app/controllers/compras_controller.rb
class ComprasController < ApplicationController

  def index
		@compras = Compra.all 
  end

  def show
  end

  def new
		print "custom print \n"
		if params != nil && params[:compra] != nil
			print params[:compra][:restaurante_id]
		print "\n"
		@rest_id = params[:compra][:restaurante_id]
		end
		@compra = Compra.new
  end

  def edit
  end

  def create
		pars = compra_params
		pars[:cantidad_personas] = pars[:cantidad_personas].to_i
		pars[:valorComun] = pars[:valorComun].to_f
		@compra = Compra.new({
			:restaurante_id => pars[:restaurante_id], 
			:cantidad_personas => pars[:cantidad_personas],
			:valorComun => pars[:valorComun],
			:valor => pars[:valor],
			:fecha => pars[:fecha],
			:descripcion => pars[:descripcion]
		})
		personas = []
		pars[:producto_id].each do |producto_id|
			producto = Producto.find(producto_id)
			for i in 1..producto.porciones do
				persona = Persona.find(pars[:persona_id].shift)
				detalleCompra = DetalleCompra.new({"persona" => persona, "producto" => producto})
				@compra.detalle_compras.append(detalleCompra)
				persona.saldo += producto.precio / producto.porciones
				persona.save
				if !personas.include?(persona.id)
					personas.push(persona.id)
				end
			end
		end
		if pars[:valorComun] > 0
			personas.each do |persona_id|
				persona = Persona.find(persona_id)
				persona.saldo += pars[:valorComun] / pars[:cantidad_personas]
				persona.save
			end
		end
		if @compra.save
			redirect_to compras_path
		else
			render :action => "new"
		end
  end

  def update
  end

  def destroy
  end

	private
		def compra_params
			params.require(:compra).permit(:fecha, :restaurante_id, :descripcion, :valorComun, :cantidad_personas, :valor, :producto_id => [], :persona_id => [])
		end
end

LetsHangOut/app/controllers/pagos_controller.rb
class PagosController < ApplicationController

  def index
		@pagos = Pago.all
  end

  def show
  end

  def new
		@pago = Pago.new
  end

  def edit
  end

  def create
		pars = pago_params
		@pago = Pago.new({
			:persona_id => pars[:persona_id],
			:valor => pars[:valor],
			:fecha => pars[:fecha],
			:confirmacion_url => pars[:confirmacion].original_filename
		})
		if @pago.save
			@pago.persona.saldo -= @pago.valor
			@pago.persona.save
			upload
			redirect_to pagos_path
		else
			render :action => "new"
		end
  end

  def update
  end

  def destroy
  end

	private
		def pago_params
			params.require(:pago).permit(:persona_id, :valor, :fecha, :confirmacion)
		end
		
		def upload
			uploaded_io = pago_params[:confirmacion]
			File.open(Rails.root.join("public", "confirmaciones", uploaded_io.original_filename), "wb") do |file|
				file.write(uploaded_io.read)
			end
		end
end

LetsHangOut/app/controllers/personas_controller.rb
class PersonasController < ApplicationController

  def index
    @personas = Persona.all
  end

  def show
  end

  def new
    @persona = Persona.new
  end

  def edit
  end

  def create
    @persona = Persona.new(persona_params)
    if @persona.save
      redirect_to personas_path
    else
      render "new"
    end
  end

  def update
  end

  def destroy
  end

  private
    def persona_params
      params.require(:persona).permit(:nombre, :alias)
    end
end

LetsHangOut/app/controllers/productos_controller.rb
class ProductosController < ApplicationController

  def index
    @productos = Producto.all
  end

  def show
  end

  def new
    @producto = Producto.new
  end

  def edit
  end

  def create
    @producto = Producto.new(producto_params)
    if @producto.save
      redirect_to productos_path
    else
      render "new"
    end
  end

  def update
  end

  def destroy
  end

  private
  	def producto_params
    	params.require(:producto).permit(:restaurante_id, :nombre, :precio, :porciones)
		end
end

LetsHangOut/app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController

  def index
    @restaurantes = Restaurante.all
  end

  def show
  end

  def new
    @restaurante = Restaurante.new
  end

  def edit
  end

  def create
    @restaurante = Restaurante.new(restaurante_params)
    if @restaurante.save
      redirect_to restaurantes_path
    else
      render "new"
    end
  end

  def update
  end

  def destroy
  end

  private
    def restaurante_params
      params.require(:restaurante).permit(:nombre)
    end
end

LetsHangOut/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

LetsHangOut/app/helpers/application_helper.rb
module ApplicationHelper

  def check_nulity(value, returnIfNull)
    if value != nil
      return value
    else
      return returnIfNull
    end
  end

end

LetsHangOut/app/helpers/compras_helper.rb
module ComprasHelper
end

LetsHangOut/app/helpers/pagos_helper.rb
module PagosHelper
end

LetsHangOut/app/helpers/personas_helper.rb
module PersonasHelper
end

LetsHangOut/app/helpers/productos_helper.rb
module ProductosHelper
end

LetsHangOut/app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

LetsHangOut/app/helpers/salidas_helper.rb
module SalidasHelper
end

LetsHangOut/app/helpers/welcome_helper.rb
module WelcomeHelper
end

LetsHangOut/app/views/compras/_form.html.erb
<SCRIPT>
	<%
		@rest_id = check_nulity(@rest_id, 1)
  	productos = Producto.where(restaurante_id: @rest_id).all.collect{|p| [p.id.to_i, p.nombre, p.precio, p.porciones]}
  	personas = Persona.all.collect{|p| [p.alias, p.id.to_i]}
	%>
	var productos = <%= productos.collect{|p| [p[0], p[2], p[3]]} %>
</SCRIPT>
<DIV class="form" id="salida_form">
  <%= form_with model: @compra, local: true do |form| %>
    <% if @compra.errors.any? %>
      <DIV id="error_explanation">
        <H2>
          <%= @compra.errors.count %>
          <%= @compra.errors.count!=1 ? "error" : "errores" %>
          evitaron que esta salida fuera guardada:
        </H2>
        <UL>
          <% @compra.errors.full_messages.each do |msg| %>
            <LI><%= msg %></LI>
          <% end %>
        </UL>
      </DIV>
    <% end %>
    <TABLE>
      <TR>
				<TH><%= form.label :fecha %></TH>
				<TH><%= form.label :restaurante %></TH>
			</TR>
			<TR>
				<TD><%= form.date_field :fecha, :value => Date.today %></TD>
        <TD><%= form.select :restaurante_id, options_for_select(Restaurante.all.collect {|p| [p.nombre, p.id, {}]}, :selected => check_nulity(@rest_id, 1)), {}, {:onchange => "actualizarProductos()"} %></TD>
      </TR>
			<TR>
				<TH colspan="2"><%= form.label :descripción %></TH>
			</TR>
			<TR>
				<TD colspan="2"><%= form.text_area :descripcion, {:style => "width: 100%;"} %></TD>
			</TR>
		</TABLE>
		<TABLE>
			<TR>
				<TD colspan="3">
					<SPAN class="add" onclick="agregarProducto(this.parentElement.parentElement)">Agregar Producto</SPAN> | 
					<SPAN class="rmv" onclick="removerProducto();">Remover Producto</SPAN>
				</TD>
			</TR>
		</TABLE>
		<TABLE>
			<TR>
				<TH>Valor<BR>Común</TH>
				<TH>Número de<BR>Personas</TH>
				<TH><%= form.label :total %></TH>
			</TR>
			<TR>
				<TD><%= form.number_field :valorComun, {:onkeyup => "actualizarTotal();", :style => "width: 65px;"} %></TD>
				<TD><%= form.number_field :cantidad_personas, {:readonly => true, :style => "width: 65px;"} %></TD>
				<TD><%= form.number_field :valor, {:readonly => true, :style => "width: 65px;"} %></TD>
			</TR>
      <TR>
        <TD colspan=2><%= form.submit "Guardar" %></TD>
      </TR>
    </TABLE>
	<SCRIPT>
  	function actualizarProductos() {
			var form = $("form")[0];
			form.setAttribute("method", "get");
			form.setAttribute("action", "/compras/new");
			form.submit();
  	}
		function getProducto(id) {
			var i;
			for(i=0; i<productos.length; i++){
				if(productos[i][0] == parseInt(id)){
					return productos[i];
				}
			}
		}
		function renderPersonas(tr, productoId) {
			var i;
			var producto = getProducto(productoId);
			var tds = $("td", tr)
			for(i=0; i<Math.max(producto[2], tds.length-1); i++){
				var td;
				if(i>=tds.length-1){
					td = document.createElement("td");
					td.innerHTML = `
						<%= form.select :persona_id, options_for_select(personas), {}, {
							:class => "persona", 
							:name => "compra[persona_id][]",
							:onchange => "actualizarPersonas();"
						} %>
					`;
					tr.appendChild(td);
				}else{
					if(i>producto[2]-1){
						td = tds[i+1];
						tr.removeChild(td);
					}
				}
			}
			actualizarPersonas();
		}
		function agregarProducto(insertBefore){
			var tr = document.createElement("tr");
			tr.setAttribute("class", "producto")
			tr.innerHTML = `<TD><%= 
				form.select :producto_id, options_for_select(productos.collect{|p| [p[1], p[0]]}), {}, {
					:class => "producto",
					:name => "compra[producto_id][]",
					:onchange => "
						renderPersonas(this.parentElement.parentElement, this.value);
						actualizarTotal();
					"
				}
			 %></TD>`;
			var table = $("tbody")[1]
			table.insertBefore(tr, insertBefore)
			renderPersonas(tr, productos[0]);
			actualizarTotal();
		}
		function removerProducto(){
			trProductos = $("tr.producto");
			if(trProductos.length >1){
				$("tbody")[1].removeChild(trProductos.last()[0]);
			}
			actualizarTotal();
		}
		function actualizarTotal(){
			var total = $("#compra_valor")[0];
			var valorComunField = $("#compra_valorComun")[0];
			var selectProductos = $("select.producto");
			var valorComun = valorComunField.value != "" ? parseInt(valorComunField.value) : 0;
			var i;
			var j;
			var val = valorComun;
			for(i=0; i<selectProductos.length; i++){
				for(j=0; j<productos.length; j++){
					if(productos[j][0] == selectProductos[i].value){
						val += productos[j][1]
						break;
					}
				}
			}
			total.value = val;
		}
		function actualizarPersonas(){
			var personasInput = $("#compra_cantidad_personas")[0];
			var selectPersonas = $("select.persona");
			var personas = [];
			var i;
			for(i=0; i<selectPersonas.length; i++){
				if(!personas.includes(selectPersonas[i].value)){
					personas.push(selectPersonas[i].value);
				}
			}
			personasInput.value = personas.length;
		} 
		agregarProducto($("span.add")[0].parentNode.parentNode, 0)
		actualizarTotal();
	</SCRIPT>
	<% end %>
</DIV>

LetsHangOut/app/views/compras/create.html.erb
<h1>Salidas#create</h1>
<p>Find me in app/views/salidas/create.html.erb</p>

LetsHangOut/app/views/compras/destroy.html.erb
<h1>Salidas#destroy</h1>
<p>Find me in app/views/salidas/destroy.html.erb</p>

LetsHangOut/app/views/compras/edit.html.erb
<h1>Salidas#edit</h1>
<p>Find me in app/views/salidas/edit.html.erb</p>

LetsHangOut/app/views/compras/index.html.erb
<DIV class= "index" id="compra_index">
  <H1>Lista de Salidas</H1>
  <%= link_to "Nueva", new_compra_path %> |
  <%= link_to "Regresar", root_path %>
  <TABLE>
    <TR>
			<TH>Fecha</TH>
      <TH>Restaurante</TH>
      <TH>¿Cuántos?</TH>
			<TH>Descripción</TH>
      <TH>Total</TH>
    </TR>
    <% @compras.each do |compra| %>
      <TR>
				<TD><%= compra.fecha %></TD>
        <TD><%= compra.restaurante.nombre %></TD>
        <TD><%= compra.cantidad_personas %></TD>
				<TD><%= compra.descripcion %></TD>
        <TD><%= compra.valor %></TD>
      </TR>
    <% end %>
  </TABLE>
</DIV>

LetsHangOut/app/views/compras/new.html.erb
<DIV class="new" id="compra_new">
  <h1>Nueva Salida</h1>
  <%= render "form" %>
  <%= link_to "Regresar", compras_path %>
</DIV>

LetsHangOut/app/views/compras/show.html.erb
<h1>Salidas#show</h1>
<p>Find me in app/views/salidas/show.html.erb</p>

LetsHangOut/app/views/compras/update.html.erb
<h1>Salidas#update</h1>
<p>Find me in app/views/salidas/update.html.erb</p>

LetsHangOut/app/views/pagos/_form.html.erb
<DIV class="form" id="pago_form">
	<%= form_with model: @pago, local: true do |form| %>
		<% if @pago.errors.any? %>
			<DIV id="error_explanation">
        <H2>
          <%= @pago.errors.count %>
          <%= @pago.errors.count!=1 ? "error" : "errores" %>
          evitaron que esta persona fuera guardada:
        </H2>
        <UL>
          <% @pago.errors.full_messages.each do |msg| %>
            <LI><%= msg %></LI>
          <% end %>
        </UL>
      </DIV>
		<% end %>
		<P>
			<%= form.label :fecha %>
			<BR>
			<%= form.date_field :fecha, {:value => Date.today} %>
		</P>
		<P>
			<%= form.label :persona %>
			<BR>
			<%= form.select :persona_id, options_for_select(Persona.all.collect{|p| [p.alias, p.id]}) %>
		</P>
		<P>
			<%= form.label :valor %>
			<BR>
			<%= form.number_field :valor, {:value => "0", :step => "0.01"} %>
		</P>
		<P>
			<%= form.label :confirmación %>
			<BR>
			<%= form.file_field :confirmacion, {:accept => "image/*"} %>
		</P>
		<P>
			<%= form.submit "Guardar" %>
		</P>
	<% end %>
</DIV>

LetsHangOut/app/views/pagos/create.html.erb
<h1>Pagos#create</h1>
<p>Find me in app/views/pagos/create.html.erb</p>

LetsHangOut/app/views/pagos/destroy.html.erb
<h1>Pagos#destroy</h1>
<p>Find me in app/views/pagos/destroy.html.erb</p>

LetsHangOut/app/views/pagos/edit.html.erb
<h1>Pagos#edit</h1>
<p>Find me in app/views/pagos/edit.html.erb</p>

LetsHangOut/app/views/pagos/index.html.erb
<DIV class="index", id="pago_index">
	<h1>Lista de Pagosx</h1>
	<%= link_to "Nuevo", new_pago_path %> | 
	<%= link_to "Regresar", root_path %>
	<TABLE>
		<TR>
			<TH>Fecha</TH>
			<TH>Persona</TH>
			<TH>Valor</TH>
			<TH>Confirmación</TH>
		</TR>
		<% @pagos.each do |pago| %>
			<TR>
				<TD><%= pago.fecha %></TD>
				<TD><%= pago.persona.nombre %></TD>
				<TD><%= pago.valor %></TD>
				<TD><%= pago.confirmacion_url %></TD>
			</TR>
		<% end %>
	</TABLE>
</DIV>

LetsHangOut/app/views/pagos/new.html.erb
<DIV class="new" id="pago_new">
	<h1>Nuevo Pago</h1>
	<%= render "form" %>
	<%= link_to "Regresar", pagos_path %>
</DIV>

LetsHangOut/app/views/pagos/show.html.erb
<h1>Pagos#show</h1>
<p>Find me in app/views/pagos/show.html.erb</p>

LetsHangOut/app/views/pagos/update.html.erb
<h1>Pagos#update</h1>
<p>Find me in app/views/pagos/update.html.erb</p>

LetsHangOut/app/views/personas/_form.html.erb
<DIV class="form" id="persona_form">
  <%= form_with model: @persona, local: true do |form| %>
    <% if @persona.errors.any? %>
      <DIV id="error_explanation">
        <H2>
          <%= @persona.errors.count %>
          <%= @persona.errors.count!=1 ? "error" : "errores" %>
          evitaron que esta persona fuera guardada:
        </H2>
        <UL>
          <% @persona.errors.full_messages.each do |msg| %>
            <LI><%= msg %></LI>
          <% end %>
        </UL>
      </DIV>
    <% end %>
    <TABLE>
      <TR>
        <TH><%= form.label :nombre %></TH>
        <TH><%= form.label :alias %></TH>
      </TR>
      <TR>
        <TD><%= form.text_field :nombre %></TD>
        <TD><%= form.text_field :alias %></TD>
      </TR>
      <TR>
        <TD colspan=2><%= form.submit "Guardar" %></TD>
      </TR>
    </TABLE>
  <% end %>
</DIV>

LetsHangOut/app/views/personas/create.html.erb
<h1>Personas#create</h1>
<p>Find me in app/views/personas/create.html.erb</p>

LetsHangOut/app/views/personas/destroy.html.erb
<h1>Personas#destroy</h1>
<p>Find me in app/views/personas/destroy.html.erb</p>

LetsHangOut/app/views/personas/edit.html.erb
<h1>Personas#edit</h1>
<p>Find me in app/views/personas/edit.html.erb</p>

LetsHangOut/app/views/personas/index.html.erb
<DIV class= "index" id="persona_index">
  <H1>Lista de Personas</H1>
  <%= link_to "Nueva", new_persona_path %> |
  <%= link_to "Regresar", root_path %>
  <TABLE>
    <TR>
      <TH>Nombre</TH>
      <TH>Alias</TH>
      <TH>Saldo</TH>
    </TR>
    <% @personas.each do |persona| %>
      <TR>
        <TD><%= persona.nombre %></TD>
        <TD><%= persona.alias %></TD>
        <TD><%= persona.saldo.round(2) %></TD>
      </TR>
    <% end %>
  </TABLE>
</DIV>

LetsHangOut/app/views/personas/new.html.erb
<DIV class="new" id="persona_new">
  <h1>Nueva Persona</h1>
  <%= render "form" %>
  <%= link_to "Regresar", personas_path %>
</DIV>

LetsHangOut/app/views/personas/show.html.erb
<h1>Personas#show</h1>
<p>Find me in app/views/personas/show.html.erb</p>

LetsHangOut/app/views/personas/update.html.erb
<h1>Personas#update</h1>
<p>Find me in app/views/personas/update.html.erb</p>

LetsHangOut/app/views/productos/_form.html.erb
<DIV class="form" id="persona_form">
  <%= form_with model: @producto, local: true do |form| %>
    <% if @producto.errors.any? %>
      <DIV id="error_explanation">
        <H2>
          <%= @producto.errors.count %>
          <%= @producto.errors.count!=1 ? "error" : "errores" %>
          evitaron que esta persona fuera guardada:
        </H2>
        <UL>
          <% @producto.errors.full_messages.each do |msg| %>
            <LI><%= msg %></LI>
          <% end %>
        </UL>
      </DIV>
    <% end %>
    <TABLE>
      <TR>
        <TH><%= form.label :restaurante %></TH>
        <TH><%= form.label :nombre %></TH>
        <TH><%= form.label :precio %></TH>
        <TH><%= form.label :porciones %></TH>
      </TR>
      <TR>
        <TD><%= form.select :restaurante_id, options_for_select(Restaurante.all.collect {|r| [r.nombre, r.id.to_i]}, :selected => @producto.restaurante_id!=nil ? @producto.restaurante_id : 1)%></TD>
        <TD><%= form.text_field :nombre %></TD>
        <TD><%= form.number_field :precio, :value => check_nulity(@producto.precio, 0), min: "0", step: "0.01"  %></TD>
        <TD><%= form.number_field :porciones, :value => @producto.porciones!=nil ? @producto.porciones : 1, :min => 1, :step => 1 %></TD>
      </TR>
      <TR>
        <TD colspan=3><%= form.submit "Guardar" %></TD>
      </TR>
    </TABLE>
  <% end %>
</DIV>

LetsHangOut/app/views/productos/create.html.erb
<h1>Productos#create</h1>
<p>Find me in app/views/productos/create.html.erb</p>

LetsHangOut/app/views/productos/destroy.html.erb
<h1>Productos#destroy</h1>
<p>Find me in app/views/productos/destroy.html.erb</p>

LetsHangOut/app/views/productos/edit.html.erb
<h1>Productos#edit</h1>
<p>Find me in app/views/productos/edit.html.erb</p>

LetsHangOut/app/views/productos/index.html.erb
<DIV class= "index" id="producto_index">
  <H1>Lista de Productos</H1>
  <%= link_to "Nuevo", new_producto_path %> |
  <%= link_to "Regresar", root_path %>
  <TABLE>
    <TR>
      <TH>Restaurante</TH>
      <TH>Nombre</TH>
      <TH>Precio</TH>
      <TH>Porciones</TH>
    </TR>
    <% @productos.each do |producto| %>
      <TR>
        <TD><%= producto.restaurante.nombre %></TD>
        <TD><%= producto.nombre %></TD>
        <TD><%= producto.precio %></TD>
        <TD><%= producto.porciones %></TD>
      </TR>
    <% end %>
  </TABLE>
</DIV>

LetsHangOut/app/views/productos/new.html.erb
<DIV class="new" id="prodcto_new">
  <h1>Nuevo Producto</h1>
  <%= render "form" %>
  <%= link_to "Regresar", productos_path %>
</DIV>

LetsHangOut/app/views/productos/show.html.erb
<h1>Productos#show</h1>
<p>Find me in app/views/productos/show.html.erb</p>

LetsHangOut/app/views/productos/update.html.erb
<h1>Productos#update</h1>
<p>Find me in app/views/productos/update.html.erb</p>

LetsHangOut/app/views/restaurantes/_form.html.erb
<DIV class="form" id="restaurante_form">
  <%= form_with model: @restaurante, local: true do |form| %>
    <% if @restaurante.errors.any? %>
      <DIV id="error_explanation">
        <H2>
          <%= @restaurante.errors.count %>
          <%= @restaurante.errors.count!=1 ? "error" : "errores" %>
          evitaron que este restaurante fuera guardado:
        </H2>
        <UL>
          <% @restaurante.errors.full_messages.each do |msg| %>
            <LI><%= msg %></LI>
          <% end %>
        </UL>
      </DIV>
    <% end %>
    <TABLE>
      <TR>
        <TH><%= form.label :nombre %></TH>
      </TR>
      <TR>
        <TD><%= form.text_field :nombre %></TD>
      </TR>
      <TR>
        <TD><%= form.submit "Guardar" %></TD>
      </TR>
    </TABLE>
  <% end %>
</DIV>

LetsHangOut/app/views/restaurantes/create.html.erb
<h1>Restaurantes#create</h1>
<p>Find me in app/views/restaurantes/create.html.erb</p>

LetsHangOut/app/views/restaurantes/destroy.html.erb
<h1>Restaurantes#destroy</h1>
<p>Find me in app/views/restaurantes/destroy.html.erb</p>

LetsHangOut/app/views/restaurantes/edit.html.erb
<h1>Restaurantes#edit</h1>
<p>Find me in app/views/restaurantes/edit.html.erb</p>

LetsHangOut/app/views/restaurantes/index.html.erb
<DIV class= "index" id="restaurante_index">
  <H1>Lista de Restaurantes</H1>
  <%= link_to "Nuevo", new_restaurante_path %> |
  <%= link_to "Regresar", root_path %>
  <TABLE>
    <TR>
      <TH>Nombre</TH>
    </TR>
    <% @restaurantes.each do |restaurante| %>
      <TR>
        <TD><%= restaurante.nombre %></TD>
      </TR>
    <% end %>
  </TABLE>
</DIV>

LetsHangOut/app/views/restaurantes/new.html.erb
<DIV class="new" id="restaurante_new">
  <h1>Nuevo Restaurante</h1>
  <%= render "form" %>
  <%= link_to "Regresar", restaurantes_path %>
</DIV>

LetsHangOut/app/views/restaurantes/show.html.erb
<h1>Restaurantes#show</h1>
<p>Find me in app/views/restaurantes/show.html.erb</p>

LetsHangOut/app/views/restaurantes/update.html.erb
<h1>Restaurantes#update</h1>
<p>Find me in app/views/restaurantes/update.html.erb</p>

LetsHangOut/app/views/welcome/index.html.erb
<DIV class="index" id="welcome_index">
  <h1>Salimos?</h1>
  <%= link_to "Personas", controller: "personas" %><BR>
  <%= link_to "Restaurantes", controller: "restaurantes" %><BR>
  <%= link_to "Productos", controller: "productos" %></BR>
	<%= link_to "Salidas", controller: "compras" %><BR>
	<%= link_to "Pagos", controller: "pagos" %>
</DIV>